name: grocery
channels:
  - defaults
  - conda-forge
dependencies:
  - Flask=2.2.3
  - Flask-Excel=0.0.7
  - Flask-Login=0.6.2
  - Flask-Principal=0.4.0
  - Flask-RESTful=0.3.10
  - Flask-Security-Too=5.1.2
  - Flask-SQLAlchemy=3.0.3
  - Flask-WTF=1.1.1
  - celery
  - Jinja2=3.1.2
  - SQLAlchemy=2.0.6
  - email-validator==1.3.1
  - python=3.9
